name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
     # - run: npm install 
      - run: make setup
      - run: npm run lint
      - run: make start
